name: Valida imagem docker

on: [pull_request]

jobs:
  build:
    environment: docker
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: downcase repository
      run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

    - name: Dockerfile lint check
      run: docker run --rm -i hadolint/hadolint < Dockerfile
   
    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: ghcr.io/${{ env.REPO }}
        tag-sha: true

    - name: Login to Github packages  
      uses: docker/login-action@v1.3.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_PAT }}
        
    - name: Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master    

    - name: Build da imagem docker
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:  ghcr.io/${{ env.REPO }}:pr-${{ github.event.number }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        
    - name: Trivy scan
      uses: homoluctus/gitrivy@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        image: ghcr.io/${{ env.REPO }}:pr-${{ github.event.number }}
