name: Testes

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar pacotes
      run: yarn install --frozen-lockfile

    - name: Rodar testes
      run: yarn test
    
    - name: Validar code-style
      run: yarn lint